export const posters = [
    {
        id: 1,
        title: 'PostCard V1',
        price: 23.45 ,
        quantity: 1,
        type: "PostCard",
        aboutText: 'Sending a travel postcard to a loved one is truly a thoughtful gesture that can bring joy and inspiration. Inspiration can come in the form of taking a break from the normal routine, while being reminded of the more adventurous and exotic destinations around the world.',
        imgUrl: 'https://websitedemos.net/earth-store-02/wp-content/uploads/sites/1171/2022/11/Postcard1.jpg',
    },
    {
        id: 2,
        title: 'PostCard V2',
        price: 18.34 ,
        quantity: 1,
        type: "PostCard",
        aboutText: 'Sending a travel postcard to a loved one is truly a thoughtful gesture that can bring joy and inspiration. Inspiration can come in the form of taking a break from the normal routine, while being reminded of the more adventurous and exotic destinations around the world.',
        imgUrl: 'https://websitedemos.net/earth-store-02/wp-content/uploads/sites/1171/2022/11/Postcard3.jpg',
    },
    {
        id: 3,
        title: 'PostCard V3',
        price: 12.98 ,
        quantity: 1,
        type: "PostCard",
        aboutText: 'Sending a travel postcard to a loved one is truly a thoughtful gesture that can bring joy and inspiration. Inspiration can come in the form of taking a break from the normal routine, while being reminded of the more adventurous and exotic destinations around the world.',
        imgUrl: 'https://websitedemos.net/earth-store-02/wp-content/uploads/sites/1171/2022/11/Postcard1.jpg',
    },
    {
        id: 4,
        title: 'Poster V1',
        price: 17.67 ,
        quantity: 1,
        type: "Poster",
        aboutText: 'Inspirational posters are a great way to be inspired and encouraged to take on new challenges and adventures. Hang up a poster at home or in the office to be reminded how much beauty awaits in the world, luring you out of your comfort zone and into a world where possibility re',
        imgUrl: 'https://websitedemos.net/earth-store-02/wp-content/uploads/sites/1171/2022/10/Poster5-1000x667.jpg',
    },
    {
        id: 5,
        title: 'Poster V2',
        price: 19.37 ,
        quantity: 1,
        type: "Poster",
        aboutText: 'Inspirational posters are a great way to be inspired and encouraged to take on new challenges and adventures. Hang up a poster at home or in the office to be reminded how much beauty awaits in the world, luring you out of your comfort zone and into a world where possibility resides.',
        imgUrl: 'https://websitedemos.net/earth-store-02/wp-content/uploads/sites/1171/2022/10/Poster1.jpg',
    },
    {
        id: 6,
        title: 'Poster V3',
        price: 10.99 ,
        quantity: 1,
        type: "Poster",
        aboutText: 'Inspirational posters are a great way to be inspired and encouraged to take on new challenges and adventures. Hang up a poster at home or in the office to be reminded how much beauty awaits in the world, luring you out of your comfort zone and into a world where possibility resides.',
        imgUrl: 'https://websitedemos.net/earth-store-02/wp-content/uploads/sites/1171/2022/10/Poster5.jpg',
    },
]